###Stop the services that are not used
- name: Get the list of services
  service_facts:

- name: Ensure cloud-init is stoped and disabled
  service: name=cloud-init state=stopped enabled=no
  when: "'cloud-init.service' in services"

- name: Remove "cloud-init" package
  ansible.builtin.apt:
    name: cloud-init
    purge: true
    state: absent

- name: Installing Packages
  apt:
    name: "{{ packages }}"
    state: "present"
    force_apt_get: yes
  vars:
    packages:
      - 'gpgv'

- name: Update apt packages list
  apt:
    update_cache: yes

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present
    
- name: set as default locale
  command: localedef -i en_US -f UTF-8 en_US.UTF-8

#dir struct
- name: create directory admin
  file:
    path: "/home/admin"
    state: directory