- name: Set host name
  hostname:
    name: "{{ project_cache_name }}"
  when: project_plan != "small"

- name: Update apt packages list
  apt:
    update_cache: yes

- name: Installing Redis Server Packages
  apt:
    name: "{{ packages }}"
    state: "present"
    force_apt_get: yes
  vars:
    packages:
      - 'redis-server'

- name: Enable private network access
  replace:
    path: "/etc/redis/redis.conf"
    regexp: "bind 127.0.0.1"
    replace: "bind {{ project_cache_endpoint }} 127.0.0.1"
  notify:
  - Restart Redis Service